from aiogram.fsm.state import State, StatesGroup

class SetConfigsToBot(StatesGroup):
    set_password = State()
    set_name = State()
    set_notification = State()
    set_user_names = State()
    edit_user_names = State()
    set_new_username = State()
    set_points_names = State()
    set_points_score = State()
    set_points_min = State()
    set_new_pointname = State()
    set_checkpoint = State()
    set_notification1 = State()
    set_notification2 = State()
    set_notification_final = State()
    set_redline_hour = State()
    set_redline_day = State()
    set_redline_final = State()
    set_changecheckpoint = State()
    set_rowbonus = State()
    set_colbonus = State()
    set_minsbonus = State()
    set_msg_to_usr = State()
    set_msgtime_to_usr = State()
    set_msgdatetime_to_usr = State()
    set_msgtheme_to_usr = State()
